[package]
name = "sysx"
version = "0.3.0"
edition = "2021"

[dependencies]
rand = "0.9.0"
num = "0.4.3"

[dependencies.regex]
version = "1.11.1"
default-features = false
features = ["std", "unicode-perl"]

[dependencies.winapi]
version = "0.3.9"
features = ["sysinfoapi"]
