[package]
name = "lrst"
version = "0.2.2"
edition = "2021"

[dependencies]
rand = "0.9.0"
num = "0.4.3"
sysinfo = "0.33.1"

[dependencies.regex]
version = "1.11.1"
default-features = false
features = ["std", "unicode-perl"]

[dependencies.winapi]
version = "0.3.9"
features = ["sysinfoapi"]
